export const SWITCH_SCREEN = 'SWITCH_SCREEN';
// export const SWITCH_METRIC = 'SWITCH_METRIC';
export const SWITCH_DATASCREEN = 'SWITCH_DATASCREEN';
export const SWITCH_MAINTAB = 'SWITCH_MAINTAB';

// export const SWITCH_SERVICE = 'SWITCH_SERVICE';
export const TOGGLE_SERVICE = 'TOGGLE_SERVICE';
export const TOGGLE_METRIC = 'TOGGLE_METRIC';

export const CLEAR_DATA = 'CLEAR_DATA';

export const TOGGLE_GRAPH = 'TOGGLE_GRAPH';

export const TOGGLE_EDIT_CARD_MODE = 'TOGGLE_EDIT_CARD_MODE';
export const TOGGLE_EDIT_METRIC_MODE = 'TOGGLE_EDIT_METRIC_MODE';

export const DELIVER_DATA = 'DELIVER_DATA';